apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfd
  name: ctf-pv-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: "ctfd-logs-efs-az1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ctfd
  name: ctfd-pv-uploads
  annotations:
    volume.beta.kubernetes.io/storage-class: "ctfd-uploads-efs-az1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
